export enum EnsVariableNameEnum {
    //@Todo mudar nome
    PRODUCT_DATA_ENS_TYPE = "PRODUCT_DATA_ENS_TYPE",
    DIELECTRIC_TEST_CHARACTERISTIC_LIST_TYPE = "DIELECTRIC_TEST_CHARACTERISTIC_LIST_TYPE",
    FUNCTIONAL_TEST_CHARACTERISTIC_LIST_TYPE = "FUNCTIONAL_TEST_CHARACTERISTIC_LIST_TYPE",
    LOAD_TEST_CHARACTERISTIC_LIST_TYPE = "LOAD_TEST_CHARACTERISTIC_LIST_TYPE",
    RENEABLE_TEST_CHARACTERISTIC_LIST_TYPE = "RENEABLE_TEST_CHARACTERISTIC_LIST_TYPE"
}