export enum TagEnum {
  OneTag = "OneTag",
  LeafEnsSetupTag = "LeafEnsSetupTag",
  LeafEthernetCommunicationTag = "LeafEthernetCommunicationTag",
  LeafIOLinkCommunicationTag = "LeafIOLinkCommunicationTag",
  LeafModbusCommunicationTag = "LeafModbusCommunicationTag",
  LeafMultipleRegisterCompareTag = "LeafMultipleRegisterCompareTag",
  LeafMultipleWriteTag = "LeafMultipleWriteTag",
  LeafRegisterCompareTag = "LeafRegisterCompareTag",
  LeafStringWriteTag = "LeafStringWriteTag",
  LeafTestTag = "LeafTestTag",
  LeafUserConfirmationTag = "LeafUserConfirmationTag",
  LeafUserInputTag = "LeafUserInputTag",
  LeafVariableCompareTag = "LeafVariableCompareTag",
  LeafVariableStringWriteTag = "LeafVariableStringWriteTag",
  LeafVariableWriteTag = "LeafVariableWriteTag",
  LeafWriteTag = "LeafWriteTag",
}